### ISSUE TITLE
Not functional no more :(

### ISSUE THREAD

**Issue by Milkywastaken** [0ff5/Uncopylocker-game-scraper-robox#3]
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=1400&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=1000&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=600&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=400&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=1200&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=200&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=800&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=0&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=1800&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))

[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=2000&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=2200&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=2400&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=2600&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=2800&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=3000&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=3200&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=3400&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=3600&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))

[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=1600&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=3800&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=4000&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))

[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=4200&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))

[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=4400&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=4600&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=4800&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=5000&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=5200&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))

[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=5400&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=5600&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=5800&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=6000&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=6200&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))

[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=6400&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=6600&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=6800&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=7000&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))

[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=7200&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))

[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=7400&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=7600&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=7800&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=8000&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=8200&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))

[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=8400&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=8600&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=8800&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=9000&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))

[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=9200&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))

[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=9400&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))
[31m[ERROR] Failed to search for games: HTTPSConnectionPool(host='www.roblox.com', port=443): Max retries exceeded with url: /games/list-json?keyword=pls%20donate&startRows=9600&maxRows=200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1002)')))

**Comment by 0ff5** [comment]
roblox removed the api , i'll try to fix it

**Comment by Milkywastaken** [comment]
Is this API fixed?
